feat (sshstart): add --restart tag

diff --git a/bin/sshstart b/bin/sshstart
--- a/bin/sshstart
+++ b/bin/sshstart
@@ -1,27 +1,69 @@
 #!/bin/bash
 
-if [[ "$1" == "mount" ]]; then
-  mount_flag=mount
-  shift
-fi
+main() {
+  local will_restart
 
-if pgrep -x "sshd" >/dev/null
-then
-  echo "sshd already is running"
+  while [[ "$#" -gt 0 ]]; do
+    case $1 in
+        -r|--restart) will_restart=0 ;;
+        *) break ;;
+    esac
+    shift
+  done
+
+  if [[ "$1" == "mount" ]]; then
+    mount_flag=mount
+    shift
+  fi
+
+  [ $will_restart ] && {
+    if pgrep -x "sshd" >/dev/null
+    then
+      echo "stopping sshd"
+      sudo killall sshd
+    fi
+  }
+
+  if pgrep -x "sshd" >/dev/null
+  then
+    echo "sshd already is running"
+  else
+    echo "start sshd server"
+    # build authorized_key
+    if [[ $EUID -ne 0 ]]; then
+      sudo chown ride:ride /tmp
+    fi
+    chmod 755 /tmp
+
+    curl -sSL -o /tmp/authorized_keys https://github.com/laseryuan.keys
+    if [[ "$mount_flag" != "mount" ]]; then
+      echo "force user tmux a"
+      sed -i -e 's/^/command="tmux a" /' /tmp/authorized_keys
+    fi
+    chmod 600 /tmp/authorized_keys
+
+    sudo /usr/sbin/sshd -o AuthorizedKeysFile=/tmp/authorized_keys -o PasswordAuthentication=no
+  fi
+}
+
+test (){
+  function pgrep {
+    return 0
+    echo "calling: ssh $@"
+  }
+  function sudo {
+    echo "calling: sudo $@"
+  }
+
+  if ! [[ $(main --restart mount ) =~ "stopping sshd" ]]; then
+    echo "TEST FAILURE: --restart"
+    exit 1
+  fi
+  echo test succeed!
+}
+
+if [[ "$1" = "test" ]]; then
+  test "$@"
 else
-  echo "start sshd server"
-  # build authorized_key
-  if [[ $EUID -ne 0 ]]; then
-    sudo chown ride:ride /tmp
-  fi
-  chmod 755 /tmp
-
-  curl -sSL -o /tmp/authorized_keys https://github.com/laseryuan.keys
-  if [[ "$mount_flag" != "mount" ]]; then
-    echo "force user tmux a"
-    sed -i -e 's/^/command="tmux a" /' /tmp/authorized_keys
-  fi
-  chmod 600 /tmp/authorized_keys
-
-  sudo /usr/sbin/sshd -o AuthorizedKeysFile=/tmp/authorized_keys -o PasswordAuthentication=no
+  main "$@"
 fi
